import { fetchJson } from "./verify";

export interface LibraryNodeRef {
  id: string;
  doc_no: string;
  title: string;
  docs: number;
  bytes: number;
}

export interface LibraryGroup {
  name: string;
  roots: string[];
  docs: number;
  bytes: number;
}

export interface LibraryTocSection {
  id: string;
  doc_no: string;
  title: string;
  docs: number;
}

export interface LibraryTocArticle extends LibraryTocSection {
  sections: LibraryTocSection[];
}

export interface LibraryTocScope extends LibraryTocSection {
  articles: LibraryTocArticle[];
}

export interface LibraryData {
  atlasCommit: string;
  generatedAt: string;
  totals: { docs: number; bytes: number; glossaryTerms: number };
  docTypes: [string, number][];
  scopes: LibraryNodeRef[];
  groups: LibraryGroup[];
  primes: LibraryNodeRef[];
  executors: LibraryNodeRef[];
  neededResearch: { id: string; doc_no: string; title: string }[];
  toc: LibraryTocScope[];
}

// library.json is generated by scripts/aux/atlas-shape.mjs and served from the
// app root (not the sha-keyed atlas base) until the P1 build pass wires it
// into the artifact pipeline — see docs/plans/atlas-library.md.
let cached: Promise<LibraryData> | null = null;

export function loadLibrary(): Promise<LibraryData> {
  if (!cached) {
    cached = fetchJson<LibraryData>(`${import.meta.env.BASE_URL}library.json`, "library.json").catch((err) => {
      cached = null; // don't cache the rejection — retry on next call
      throw err;
    });
  }
  return cached;
}
