// Potential Mistakes — suspected defects in the Atlas source text.
//
// Unlike every other report here, this one is NOT derived from the live atlas
// at load time. public/potential-mistakes.json is a hand-run LLM artifact:
// the findings were produced by an LLM sweep of the atlas at one pinned commit
// and are regenerated by re-running that sweep by hand, never automatically on
// an atlas bump. That makes staleness the report's central UX problem, so the
// one thing we DO recompute client-side is each finding's relationship to the
// atlas currently being served (see resolveMistakes): a finding whose UUID no
// longer resolves, or whose doc has been renumbered since, is flagged rather
// than silently shown as if still current.
//
// Findings describe what the atlas SAYS; they are SAbR's reading of it, not
// atlas text. Every row carries its own doc_no + UUID + atlas link so each
// claim is checkable against the source in context.

import type { AtlasNode } from "../types";
import { toCSV } from "./csv";
import { atlasUrlOrEmpty } from "./routes";
import type { SearchField } from "./reportFilter";

export type MistakeSeverity = "high" | "medium" | "low";
export type MistakePass = "language" | "factual" | "deterministic";

/** One finding, exactly as stored in public/potential-mistakes.json. */
export interface Mistake {
  id: string;
  docNo: string;
  /** null for a corpus-wide finding that spans documents (no single target). */
  uuid: string | null;
  file: string;
  category: string;
  severity: MistakeSeverity;
  pass: MistakePass;
  quote: string;
  issue: string;
  /** null when the finding needs an author decision rather than a known edit. */
  fix: string | null;
}

export interface MistakesFile {
  generatedAt: string;
  atlasSha: string;
  documentsScanned: number;
  note: string;
  passes: Record<MistakePass, string>;
  findings: Mistake[];
}

/** How a stored finding lines up with the atlas currently being served. */
export type MistakeStatus =
  | "current" // doc still exists at the recorded doc_no
  | "renumbered" // doc still exists, but its doc_no changed since the sweep
  | "missing" // UUID no longer in the atlas — doc deleted, or the finding is stale
  | "corpus"; // finding spans documents; nothing single to resolve

export interface MistakeRow extends Mistake {
  status: MistakeStatus;
  /** Live doc_no when resolvable, else "". Differs from docNo when renumbered. */
  currentDocNo: string;
  /** Live title when resolvable, else "". */
  title: string;
}

export const SEVERITIES: readonly MistakeSeverity[] = ["high", "medium", "low"];
export const PASSES: readonly MistakePass[] = ["language", "factual", "deterministic"];

// Display order is roughly "most substantive first" — a wrong number or a
// wrong address matters more than a missing comma.
export const CATEGORIES = [
  "numeric",
  "entity",
  "governance",
  "contradiction",
  "structural",
  "xref",
  "stale",
  "placeholder",
  "copy-paste",
  "wrong-word",
  "typo",
  "grammar",
  "markdown",
  "naming",
  "duplication",
] as const;
export type MistakeCategory = (typeof CATEGORIES)[number];

export const CATEGORY_LABELS: Record<string, string> = {
  numeric: "Numeric / formula",
  entity: "Wrong entity or address",
  governance: "Governance logic",
  contradiction: "Contradiction",
  structural: "Structural",
  xref: "Broken cross-reference",
  stale: "Stale / dated",
  placeholder: "Unfilled placeholder",
  "copy-paste": "Copy-paste residue",
  "wrong-word": "Wrong word",
  typo: "Typo / spelling",
  grammar: "Grammar",
  markdown: "Broken markdown",
  naming: "Naming inconsistency",
  duplication: "Duplication",
};

export const PASS_LABELS: Record<MistakePass, string> = {
  language: "Language",
  factual: "Factual",
  deterministic: "Mechanical",
};

export const STATUS_LABELS: Record<MistakeStatus, string> = {
  current: "Doc unchanged",
  renumbered: "Renumbered since sweep",
  missing: "Doc no longer in atlas",
  corpus: "Spans documents",
};

/**
 * Joins stored findings to the atlas currently being served. This is the only
 * part of the report that is live — it is what stops a hand-run artifact from
 * quietly presenting findings about documents that have since moved or gone.
 */
export function resolveMistakes(file: MistakesFile, docs: Record<string, AtlasNode>): MistakeRow[] {
  const rows = file.findings.map((f): MistakeRow => {
    if (!f.uuid) return { ...f, status: "corpus", currentDocNo: "", title: "" };
    const doc = docs[f.uuid];
    if (!doc) return { ...f, status: "missing", currentDocNo: "", title: "" };
    return {
      ...f,
      status: doc.doc_no === f.docNo ? "current" : "renumbered",
      currentDocNo: doc.doc_no,
      title: doc.title,
    };
  });
  return sortMistakes(rows);
}

const SEV_RANK: Record<MistakeSeverity, number> = { high: 0, medium: 1, low: 2 };

/** Deterministic order: severity, then doc_no numerically, then id. */
export function sortMistakes(rows: readonly MistakeRow[]): MistakeRow[] {
  return [...rows].sort(
    (a, b) =>
      SEV_RANK[a.severity] - SEV_RANK[b.severity] ||
      a.docNo.localeCompare(b.docNo, undefined, { numeric: true }) ||
      a.id.localeCompare(b.id),
  );
}

/** Header-box text filter: doc number (recorded AND current), title, the
 *  quoted atlas text, our description, the suggested fix, and the category /
 *  pass labels so "grammar" or "factual" narrow the table too. */
export function mistakeSearchFields(r: MistakeRow): SearchField[] {
  return [
    { label: "doc no", value: r.docNo },
    { label: "current doc no", value: r.currentDocNo, hidden: true },
    { label: "title", value: r.title },
    { label: "quote", value: r.quote },
    { label: "issue", value: r.issue },
    { label: "fix", value: r.fix ?? "" },
    { label: "category", value: CATEGORY_LABELS[r.category] ?? r.category, hidden: true },
    { label: "pass", value: PASS_LABELS[r.pass], hidden: true },
    { label: "file", value: r.file, hidden: true },
  ];
}

export const MISTAKE_SEARCHES =
  "doc no · title · quoted atlas text · issue · suggested fix · category · pass";

const CSV_HEADERS = [
  "Severity",
  "Category",
  "Pass",
  "Doc No (at sweep)",
  "Doc No (current)",
  "Title",
  "Status",
  "Source File",
  "Quoted Text",
  "Issue",
  "Suggested Fix",
  "UUID",
  "Atlas Link",
];

/** One row per finding; each row carries the single doc it targets, so a UUID
 *  and Atlas Link always point at exactly one document (empty for the handful
 *  of corpus-wide findings, which by definition have no single target). */
export function mistakesToCSV(rows: readonly MistakeRow[]): string {
  return toCSV(
    CSV_HEADERS,
    rows.map((r) => [
      r.severity,
      CATEGORY_LABELS[r.category] ?? r.category,
      PASS_LABELS[r.pass],
      r.docNo,
      r.currentDocNo,
      r.title,
      STATUS_LABELS[r.status],
      r.file,
      r.quote,
      r.issue,
      r.fix ?? "",
      r.uuid ?? "",
      atlasUrlOrEmpty(r.uuid),
    ]),
  );
}

/** Per-bucket counts for the filter pills. */
export function countBy<K extends string>(rows: readonly MistakeRow[], key: (r: MistakeRow) => K): Partial<Record<K, number>> {
  const out: Partial<Record<K, number>> = {};
  for (const r of rows) out[key(r)] = (out[key(r)] ?? 0) + 1;
  return out;
}

/** Categories present in the data, in CATEGORIES display order (unknown keys last). */
export function presentCategories(rows: readonly MistakeRow[]): string[] {
  const seen = new Set(rows.map((r) => r.category));
  const known = CATEGORIES.filter((c) => seen.has(c));
  const extra = [...seen].filter((c) => !CATEGORIES.includes(c as MistakeCategory)).sort();
  return [...known, ...extra];
}
