// Renders the env registry as `.env.example`. Pure: the same groups always give
// the same bytes, which is what lets env.test.ts compare the committed file.
import type { EnvGroup, EnvVar } from "./types.ts";

const WIDTH = 80;

export const HEADER = [
  "# Generated by `pnpm env:example` from src/server/env/. Edit the declarations",
  "# there, never this file. Copy what you need into .env.local (gitignored);",
  "# Bun loads it automatically.",
];

/** Wraps prose to `# ` comment lines. A line starting with two spaces is kept as written. */
export function commentLines(text: string): string[] {
  const out: string[] = [];
  for (const para of text.split("\n")) {
    if (para.startsWith("  ")) {
      out.push(`#${para}`);
      continue;
    }
    let line = "";
    for (const word of para.split(/\s+/).filter(Boolean)) {
      if (line && line.length + 1 + word.length > WIDTH - 2) {
        out.push(`# ${line}`);
        line = word;
      } else line = line ? `${line} ${word}` : word;
    }
    out.push(line ? `# ${line}` : "#");
  }
  return out;
}

function heading(title: string): string {
  const head = `# ── ${title} `;
  return head + "─".repeat(Math.max(3, WIDTH - head.length));
}

function varLines(v: EnvVar): string[] {
  const assignment = v.example !== undefined ? `${v.name}="${v.example}"` : `# ${v.name}="${v.default ?? ""}"`;
  return [...commentLines(v.doc), assignment];
}

export function renderEnvExample(groups: EnvGroup[]): string {
  const blocks = [HEADER.join("\n")];
  for (const g of groups) {
    blocks.push([heading(g.title), ...(g.note ? commentLines(g.note) : [])].join("\n"));
    for (const v of g.vars) blocks.push(varLines(v).join("\n"));
  }
  return `${blocks.join("\n\n")}\n`;
}
