// An English word list, so the semantic leg can tell a word the reader has
// FINISHED typing from one they are still in the middle of.
//
// The search index alone cannot: it holds only the ~14.5k distinct words this
// atlas happens to use, so a perfectly ordinary word that the atlas never uses
// but that STARTS one it does — "home", "care", "learn", "water", "great" —
// looks exactly like "collater" on the way to "collateral". Measured against
// the 10k most frequent English words, 5.5% of them are in that position. They
// are also disproportionately the words a meaning search is made of, since a
// question phrased in non-atlas vocabulary is the whole point of that lane.
//
// Bundled rather than fetched: it is ~34 KB gzipped inside the search worker's
// own chunk (which already pulls in MiniSearch and a multi-megabyte index), and
// a fetch would make the answer depend on when it landed — a query typed in the
// first second would be judged by a different rule from the same query typed
// later. The list is regenerated by `pnpm words:fetch`; see src/data/common-words.txt.
import raw from "../../../../src/data/common-words.txt?raw";

/** Parse the list: one word per line, `#` comments skipped. */
export function parseCommonWords(text: string): Set<string> {
  const out = new Set<string>();
  for (const line of text.split("\n")) {
    const w = line.trim();
    if (w && !w.startsWith("#")) out.add(w);
  }
  return out;
}

const WORDS = parseCommonWords(raw);

/** Is `word` an ordinary English word — i.e. one that could be finished? */
export function isCommonWord(word: string): boolean {
  return WORDS.has(word.toLowerCase());
}

/** Test seam: the list is only useful if it actually loaded. */
export const COMMON_WORD_COUNT = WORDS.size;
