// Repo-doc renderer for the Atlas Library (docs/plans/atlas-library.md, P0).
// Renders docs/library/{toc,shape,glossary}.md + .cache/atlas-shape.json from
// the computed library shape. The app artifact (public/library.json) is NOT
// written here — that's the build pass scripts/required/build-library.mjs.
import fs from "node:fs";
import path from "node:path";
import { loadInputs, computeLibrary } from "../lib/library-shape.mjs";

const root = path.resolve(import.meta.dirname, "../..");
const inputs = loadInputs(path.join(root, "public"));
const { _internals, ...shape } = computeLibrary(inputs);
const { atlasCommit, terms } = inputs;
const { children, subtree, scopes, nr } = _internals;

const bar = (n, max, w = 28) => "█".repeat(Math.max(1, Math.round((n / max) * w)));
const kb = (b) => `${Math.round(b / 1024)} KB`;
const genNote = `> Generated by \`scripts/aux/atlas-shape.mjs\` at atlas commit \`${atlasCommit.slice(0, 7)}\` — regenerate, don't hand-edit.\n`;

// ---- toc.md ----------------------------------------------------------------
let toc = `# Atlas Table of Contents\n\n${genNote}\nChunk-aware contents to section depth, with subtree doc counts. UUIDs are the stable pointers.\n`;
for (const s of scopes) {
  const w = subtree(s.id);
  toc += `\n## ${s.doc_no} ${s.title} — ${w.docs} docs\n\n\`${s.id}\`\n\n`;
  for (const art of children.get(s.id) || []) {
    const aw = subtree(art.id);
    toc += `- **${art.doc_no} ${art.title}** (${aw.docs}) \`${art.id}\`\n`;
    for (const sec of children.get(art.id) || []) {
      if (sec.type !== "Section") continue;
      const sw = subtree(sec.id);
      toc += `  - ${sec.doc_no} ${sec.title} (${sw.docs}) \`${sec.id}\`\n`;
    }
  }
}
toc += `\n## Needed Research\n\n${nr.map((n) => `- ${n.doc_no} ${n.title} \`${n.id}\``).join("\n")}\n`;

// ---- shape.md --------------------------------------------------------------
const maxScope = Math.max(...shape.scopes.map((s) => s.docs));
const maxGroup = Math.max(...shape.groups.map((g) => g.docs));
const maxPrime = Math.max(...shape.primes.map((p) => p.docs), 1);
let sh = `# The Shape of the Atlas\n\n${genNote}\nTotal: **${shape.totals.docs} docs**, ${kb(shape.totals.bytes)} of content, ${shape.totals.glossaryTerms} glossary terms.\n`;
sh += `\n## Doc mass by scope\n\n| Scope | Docs | Content | |\n|---|---:|---:|---|\n`;
for (const s of shape.scopes) sh += `| ${s.doc_no} ${s.title} | ${s.docs} | ${kb(s.bytes)} | \`${bar(s.docs, maxScope)}\` |\n`;
sh += `\n## Doc mass by chunk group\n\nGroups per the taxonomy in \`docs/atlas-map.md\` §2 (tree-based groups only; overlays below).\n\n| Group | Docs | Content | |\n|---|---:|---:|---|\n`;
for (const g of shape.groups) sh += `| ${g.name} | ${g.docs} | ${kb(g.bytes)} | \`${bar(g.docs, maxGroup)}\` |\n`;
sh += `\n## Agent artifact weights\n\n| Artifact | Docs | Content | |\n|---|---:|---:|---|\n`;
for (const p of [...shape.primes, ...shape.executors]) sh += `| ${p.title} | ${p.docs} | ${kb(p.bytes)} | \`${bar(p.docs, maxPrime)}\` |\n`;
sh += `\n## Overlay chunks (doc types crossing the tree)\n\n| Type | Count |\n|---|---:|\n`;
for (const [t, c] of shape.docTypes) sh += `| ${t} | ${c} |\n`;
sh += `\n\`\`\`mermaid\npie showData\n  title Docs per scope\n${shape.scopes.map((s) => `  "${s.doc_no} ${s.title.replace("The ", "").replace(" Scope", "")}" : ${s.docs}`).join("\n")}\n\`\`\`\n`;

// ---- glossary.md -----------------------------------------------------------
const sorted = [...terms].sort((a, b) => a.term.localeCompare(b.term));
let gl = `# Atlas Glossary\n\n${genNote}\n${sorted.length} terms extracted from Definitions sections (source: \`public/glossary.json\`).\n\n`;
for (const t of sorted) {
  gl += `## ${t.term}\n\n${(t.content || "").trim()}\n\nSource: \`${t.nodeId}\`${t.sourceDocNo || t.docNo ? ` <!-- ${t.sourceDocNo || t.docNo} -->` : ""}\n\n`;
}

fs.mkdirSync(path.join(root, "docs/library"), { recursive: true });
fs.mkdirSync(path.join(root, ".cache"), { recursive: true });
fs.writeFileSync(path.join(root, ".cache/atlas-shape.json"), JSON.stringify({ generatedAt: new Date().toISOString(), ...shape }, null, 2));
fs.writeFileSync(path.join(root, "docs/library/toc.md"), toc);
fs.writeFileSync(path.join(root, "docs/library/shape.md"), sh);
fs.writeFileSync(path.join(root, "docs/library/glossary.md"), gl);
console.log(`atlas-shape @ ${atlasCommit.slice(0, 7)}: ${shape.totals.docs} docs, ${terms.length} terms`);
console.log("wrote .cache/atlas-shape.json, docs/library/{toc,shape,glossary}.md");
