import { fetchJson } from "@/lib/verify";

export interface ToolInfo {
  name: string;
  desc: string;
}

// Generated by `pnpm build:tools` from src/server/chat/tools/tool-registry.ts (ATLAS_TOOLS)
// — not atlas-versioned (it's app code, not atlas content), so always the flat
// BASE_URL path, same as addresses.json.
let cached: Promise<ToolInfo[]> | null = null;

export function loadTools(): Promise<ToolInfo[]> {
  if (!cached) {
    cached = fetchJson<ToolInfo[]>(`${import.meta.env.BASE_URL}tools.json`, "tools.json").catch((err) => {
      cached = null; // don't cache the rejection — retry on next call
      throw err;
    });
  }
  return cached;
}
