// Provenance callout for the Potential Mistakes report.
//
// This report is the only one on the site whose rows are NOT recomputed from
// the atlas being served, so the banner is load-bearing rather than decorative:
// it states that the findings are LLM-generated and hand-run, names the atlas
// commit they were taken at, and — when the served atlas has moved on — says
// how many rows now point at renumbered or deleted documents.
import { useId, useState } from "react";
import { useMediaQuery } from "../../hooks/useMediaQuery";
import { MOBILE_AT } from "./PotentialMistakesTable";

const SHA_LEN = 8;
const LEAD = "Generated by an LLM, and reviewed by hand — not a build artifact.";

export function MistakesProvenance({
  generatedAt,
  atlasSha,
  documentsScanned,
  total,
  drifted,
}: {
  generatedAt: string;
  atlasSha: string;
  documentsScanned: number;
  total: number;
  /** Rows whose target doc was renumbered or is gone from the served atlas. */
  drifted: number;
}) {
  const mobile = useMediaQuery(MOBILE_AT);
  const [open, setOpen] = useState(false);
  const bodyId = useId();
  const collapsed = mobile && !open;

  return (
    <div
      className="rounded border border-[var(--border)] px-3 py-2.5 mb-4 text-xs leading-relaxed"
      style={{ borderLeftWidth: "3px", borderLeftColor: "var(--warn)" }}
      data-state={mobile ? (open ? "open" : "closed") : undefined}
    >
      {mobile ? (
        <button
          type="button"
          className="text-left w-full text-tan-2"
          aria-expanded={open}
          aria-controls={bodyId}
          onClick={() => setOpen((v) => !v)}
        >
          <strong className="text-tan">{LEAD}</strong>
          {collapsed && <span aria-hidden="true">…</span>}
        </button>
      ) : (
        <p className="text-tan-2">
          <strong className="text-tan">{LEAD}</strong> <DisclaimerBody total={total} />
        </p>
      )}
      <div id={bodyId} hidden={collapsed || undefined}>
        {mobile && (
          <p className="text-tan-2 mt-1.5">
            <DisclaimerBody total={total} />
          </p>
        )}
        <p className="text-tan-3 mt-1.5">
          The sweep is <strong className="text-tan-2">re-run manually</strong>. It does{" "}
          <strong className="text-tan-2">not</strong> re-run when the Atlas updates, so these rows
          describe the Atlas as it stood at commit{" "}
          <span className="mono text-accent">{atlasSha.slice(0, SHA_LEN)}</span> on{" "}
          <span className="mono">{generatedAt}</span> ({documentsScanned.toLocaleString()}{" "}
          documents). Findings already fixed upstream will still be listed here until the next
          manual run.
        </p>
        {drifted > 0 && (
          <p className="text-tan-3 mt-1.5">
            Checked live against the Atlas currently being served:{" "}
            <span className="mono" style={{ color: "var(--warn)" }}>
              {drifted}
            </span>{" "}
            {drifted === 1 ? "finding targets a document that has" : "findings target documents that have"}{" "}
            been renumbered or removed since the sweep — filter by{" "}
            <span className="mono">Doc status</span> to see them.
          </p>
        )}
      </div>
    </div>
  );
}

function DisclaimerBody({ total }: { total: number }) {
  return (
    <>
      These {total} findings come from an automated language and consistency sweep of the Atlas
      source text. Each one is a <em>suspicion</em>, not a confirmed defect: read the quoted text
      against the linked document before acting on it.
    </>
  );
}
