// @vitest-environment jsdom
import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, cleanup, fireEvent, within } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";

Element.prototype.scrollIntoView = vi.fn();
globalThis.ResizeObserver ??= class {
  observe() {}
  unobserve() {}
  disconnect() {}
} as unknown as typeof ResizeObserver;

import type { MistakesFile } from "@/lib/potentialMistakesIndex";
import type { AtlasNode } from "@/types";

const UUID_HERE = "11111111-1111-4111-8111-111111111111";
const UUID_MOVED = "22222222-2222-4222-8222-222222222222";
const UUID_GONE = "33333333-3333-4333-8333-333333333333";

const file: MistakesFile = {
  generatedAt: "2026-09-15",
  atlasSha: "d64eca4800553d21cf61cccba3c5f5a436edd256",
  documentsScanned: 11529,
  note: "",
  passes: { language: "", factual: "", deterministic: "" },
  findings: [
    {
      id: "a", docNo: "A.1.1", uuid: UUID_HERE, file: "A.1.md", category: "typo",
      severity: "high", pass: "language", quote: "Sky Ecoystem",
      issue: "Misspelling of Ecosystem.", fix: "Sky Ecosystem",
    },
    {
      id: "b", docNo: "A.2.8", uuid: UUID_MOVED, file: "A.2.md", category: "numeric",
      severity: "medium", pass: "factual", quote: "100,000,00 USDC",
      issue: "Malformed digit grouping.", fix: null,
    },
    {
      id: "c", docNo: "A.3.1", uuid: UUID_GONE, file: "A.3.md", category: "grammar",
      severity: "high", pass: "language", quote: "documents herein defines",
      issue: "Subject/verb disagreement.", fix: "define",
    },
  ],
};

const doc = (id: string, doc_no: string, title: string): AtlasNode =>
  ({ id, doc_no, title, type: "Core", depth: 3, parentId: null, content: "", order: 0, addressRefs: [] }) as AtlasNode;

vi.mock("../../lib/docs", () => ({
  loadDocs: () =>
    Promise.resolve({
      [UUID_HERE]: doc(UUID_HERE, "A.1.1", "Website And Domain"),
      [UUID_MOVED]: doc(UUID_MOVED, "A.2.9", "Renamed Support Doc"),
    }),
}));
vi.mock("../../lib/potentialMistakesLoad", () => ({
  loadPotentialMistakes: () => Promise.resolve(file),
}));

import { PotentialMistakesReport } from "./PotentialMistakesReport";

afterEach(() => {
  cleanup();
  window.history.pushState({}, "", "/");
  Reflect.deleteProperty(window, "matchMedia");
  vi.restoreAllMocks();
});

describe("PotentialMistakesReport", () => {
  it("states that the findings are LLM-generated and not refreshed on atlas updates", async () => {
    render(<PotentialMistakesReport query="" mode="broad" />);
    expect(await screen.findByText(/Generated by an LLM/)).toBeInTheDocument();
    expect(screen.getByText(/re-run manually/)).toBeInTheDocument();
    expect(screen.getByText(/re-run when the Atlas updates/)).toBeInTheDocument();
    expect(screen.getByText(/still be listed here until the next manual run/)).toBeInTheDocument();
    // The pinned atlas commit the sweep was taken at is shown, short form.
    expect(screen.getByText("d64eca48")).toBeInTheDocument();
    expect(screen.getByText("2026-09-15")).toBeInTheDocument();
    // 80ch measure — the banner is prose, not a full-bleed stripe.
    expect(screen.getByText(/Generated by an LLM/).closest("div")).toHaveClass("max-w-[80ch]");
  });

  it("renders every finding with its quoted atlas text and explanation", async () => {
    render(<PotentialMistakesReport query="" mode="broad" />);
    expect(await screen.findByText("Sky Ecoystem")).toBeInTheDocument();
    expect(screen.getByText("Misspelling of Ecosystem.")).toBeInTheDocument();
    expect(screen.getByText("100,000,00 USDC")).toBeInTheDocument();
    expect(screen.getByText("3 of 3 findings")).toBeInTheDocument();
    expect(screen.getByRole("table").parentElement).toHaveClass("[max-width:calc(100vw-3rem)]");
  });

  it("flags a finding whose document moved or vanished since the sweep", async () => {
    render(<PotentialMistakesReport query="" mode="broad" />);
    await screen.findByText("Sky Ecoystem");
    // Scoped to the table: the same labels also appear on the Doc status pills.
    const table = within(screen.getByRole("table"));
    // Renumbered rows name the doc's current number; missing rows say so.
    expect(table.getByText(/Renumbered since sweep/)).toBeInTheDocument();
    expect(table.getByText(/→ A.2.9/)).toBeInTheDocument();
    expect(table.getByText("Doc no longer in atlas")).toBeInTheDocument();
    // …and the banner totals them, so drift is visible without filtering.
    expect(screen.getByText(/renumbered or removed since the sweep/)).toBeInTheDocument();
  });

  it("marks a finding with no suggested edit as needing an author decision", async () => {
    render(<PotentialMistakesReport query="" mode="broad" />);
    expect(await screen.findByText("needs an author decision")).toBeInTheDocument();
  });

  it("filters rows by the header query and shows the no-rows line when nothing matches", async () => {
    const { rerender } = render(<PotentialMistakesReport query="" mode="broad" />);
    await screen.findByText("Sky Ecoystem");

    rerender(<PotentialMistakesReport query="Ecoystem" mode="broad" />);
    expect(screen.getByText("1 of 3 findings")).toBeInTheDocument();
    expect(screen.queryByText("100,000,00 USDC")).not.toBeInTheDocument();

    rerender(<PotentialMistakesReport query="zzzznotfound" mode="broad" />);
    expect(screen.getByText("0 of 3 findings")).toBeInTheDocument();
  });

  it("filters by severity through a URL-synced pill", async () => {
    render(<PotentialMistakesReport query="" mode="broad" />);
    fireEvent.click(await screen.findByRole("button", { name: /^medium/ }));
    expect(screen.getByText("1 of 3 findings")).toBeInTheDocument();
    expect(window.location.search).toContain("sev=medium");
  });

  // The suggested fix only gets its own column when all three prose columns can
  // still hold 50ch. Narrow (and jsdom, which has no matchMedia) keeps it under
  // the explanation, labelled — the label is what makes it readable there.
  describe("the suggested-fix column", () => {
    const matchMedia = (matches: (query: string) => boolean) =>
      vi.fn().mockImplementation((query: string) => ({
        matches: matches(query),
        media: query,
        addEventListener: vi.fn(),
        removeEventListener: vi.fn(),
      }));

    afterEach(() => {
      Reflect.deleteProperty(window, "matchMedia");
    });

    it("stays under the explanation, labelled, when the screen is too narrow", async () => {
      window.matchMedia = matchMedia(() => false) as unknown as typeof window.matchMedia;
      render(<PotentialMistakesReport query="" mode="broad" />);
      await screen.findByText("Sky Ecoystem");
      expect(screen.queryByText("Suggested")).not.toBeInTheDocument();
      expect(screen.getAllByText(/suggested:/).length).toBeGreaterThan(0);
    });

    it("becomes its own column on a wide screen, dropping the inline label", async () => {
      window.matchMedia = matchMedia((q) => q.includes("min-width: 110rem")) as unknown as typeof window.matchMedia;
      render(<PotentialMistakesReport query="" mode="broad" />);
      await screen.findByText("Sky Ecoystem");
      expect(screen.getByRole("columnheader", { name: "Suggested" })).toBeInTheDocument();
      expect(screen.queryAllByText(/suggested:/)).toHaveLength(0);
      // The fix text itself is still there — it moved, it did not vanish.
      expect(screen.getByText("Sky Ecosystem")).toBeInTheDocument();
    });
  });

  it("on a phone shows one stacked finding at a time, not the table", async () => {
    window.matchMedia = vi.fn().mockImplementation((query: string) => ({
      matches: query.includes("max-width: 47.99rem"),
      media: query,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
    })) as unknown as typeof window.matchMedia;
    render(<PotentialMistakesReport query="" mode="broad" />);
    expect(await screen.findByText("Sky Ecoystem")).toBeInTheDocument();
    expect(screen.queryByRole("table")).not.toBeInTheDocument();
    expect(screen.getByText("1 of 3")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Next finding" })).toBeInTheDocument();
  });
});
